name: flutter_buku_app

description: Aplikasi UAS Flutter - Buku
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.7
  flutter_pdfview: ^1.2.7
  dio: ^5.4.0
  path_provider: ^2.0.15

  # WebView versi stabil terbaru
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/images/